/**
 * 补丁标志是编译器生成的优化提示。
 * 在差异更新（diff）过程中遇到带有 dynamicChildren 的块时，算法会进入“优化模式”。
 * 在此模式下，我们知道虚拟DOM（vdom）是由编译器生成的渲染函数产生的，因此算法只需处理这些补丁标志（patch flags）明确标记的更新。
 * 补丁标志可以使用 | 位运算符进行组合，并可以使用 & 运算符进行检查，例如
 *
 * ```js
 * const flag = TEXT | CLASS
 * if (flag & TEXT) { ... }
 * ```
 *
 * 请查看 '..../runtime-core/src/renderer.ts' 中的 `patchElement` 函数，了解在差异更新（diff）过程中如何处理这些标志。
 *
 * Patch flags are optimization hints generated by the compiler.
 * when a block with dynamicChildren is encountered during diff, the algorithm
 * enters "optimized mode". In this mode, we know that the vdom is produced by
 * a render function generated by the compiler, so the algorithm only needs to
 * handle updates explicitly marked by these patch flags.
 *
 * Patch flags can be combined using the | bitwise operator and can be checked
 * using the & operator, e.g.
 *
 * ```js
 * const flag = TEXT | CLASS
 * if (flag & TEXT) { ... }
 * ```
 *
 * Check the `patchElement` function in '../../runtime-core/src/renderer.ts' to see how the
 * flags are handled during diff.
 */
export const enum PatchFlags {
  /**
   * 表示具有动态文本内容（子节点快速通道）的元素。
   */
  TEXT = 1,

  /**
   * 表示具有动态 class 绑定的元素。
   */
  CLASS = 1 << 1,

  /**
   * 表示具有动态 style 绑定的元素。
   * 编译器将静态字符串样式预编译为静态对象
   * + 检测并提升内联静态对象
   * e.g. `style="color: red"` and `:style="{ color: 'red' }"` both get hoisted
   * as:
   * ```js
   * const style = { color: 'red' }
   * render() { return e('div', { style }) }
   * ```
   */
  STYLE = 1 << 2,

  /**
   * 表示一个具有非 class/style 动态属性的元素。
   * 也可以出现在具有任何动态属性（包括* class/style）的组件上。
   * 当此标志存在时，vnode还有一个dynamicProps数组，其中包含可能会更改的属性的键，
   * 以便运行时可以更快地进行差异比较（无需担心已移除的属性）
   */
  PROPS = 1 << 3,

  /**
   * 表示一个带有动态键的 props 的元素。当键发生变化时，总是需要进行完整的差异比较以移除旧键。
   * 此标志与 CLASS、STYLE 和 PROPS 互斥。
   */
  FULL_PROPS = 1 << 4,

  /**
   * 表示一个带有事件监听器的元素（需要在渲染过程中附加）
   */
  HYDRATE_EVENTS = 1 << 5,

  /**
   * 表示一个片段，其子级顺序不会改变。

   */
  STABLE_FRAGMENT = 1 << 6,

  /**
   * 表示一个包含键控或部分键控子级的片段
   */
  KEYED_FRAGMENT = 1 << 7,

  /**
   * Indicates a fragment with unkeyed children.
   * 表示一个包含未设置键的子节点的片段。
   */
  UNKEYED_FRAGMENT = 1 << 8,

  /**
   * Indicates an element that only needs non-props patching, e.g. ref or
   * directives (onVnodeXXX hooks). since every patched vnode checks for refs
   * and onVnodeXXX hooks, it simply marks the vnode so that a parent block
   * will track it.
   * 表示一个仅需进行非属性（non-props）修补的元素，例如 ref 或 * 指令（onVnodeXXX 钩子）。
   * 由于每个被修补的 vnode 都会检查 ref 和 onVnodeXXX 钩子，因此它只需标记该 vnode，以便父块对其进行跟踪。
   */
  NEED_PATCH = 1 << 9,

  /**
   * 表示一个拥有动态插槽的组件（例如引用了 v-for 迭代值的插槽，或动态插槽名）。
   * 带有此标志的组件总是会被强制更新。
   *
   * Indicates a component with dynamic slots (e.g. slot that references a v-for
   * iterated value, or dynamic slot names).
   * Components with this flag are always force updated.
   */
  DYNAMIC_SLOTS = 1 << 10,

  /**
   * 表示一个仅因为用户在模板根层级放置了注释而创建的片段。
   * 这是一个仅在开发环境使用的标志，因为注释在生产环境中会被移除。
   *
   * Indicates a fragment that was created only because the user has placed
   * comments at the root level of a template. This is a dev-only flag since
   * comments are stripped in production.
   */
  DEV_ROOT_FRAGMENT = 1 << 11,

  /**
   * 特殊标志 -------------------------------------------------------------
   * 特殊标志是负整数。它们永远不会通过位运算符进行匹配（位运算匹配只应在
   * patchFlag > 0 的分支中使用），并且它们是互斥的。检查特殊标志时，
   * 只需使用 patchFlag === FLAG 进行判断。
   *
   * SPECIAL FLAGS -------------------------------------------------------------
   * Special flags are negative integers. They are never matched against using
   * bitwise operators (bitwise matching should only happen in branches where
   * patchFlag > 0), and are mutually exclusive. When checking for a special
   * flag, simply check patchFlag === FLAG.
   */

  /**
   * 表示一个被静态提升（hoisted）的 vnode。这是一个提示，
   * 告诉 hydration 跳过整个子树，因为静态内容永远不需要更新。
   *
   * Indicates a hoisted static vnode. This is a hint for hydration to skip
   * the entire sub tree since static content never needs to be updated.
   */
  HOISTED = -1,
  /**
   * 一个特殊标志，表示 diff 算法应退出优化模式。
   * 例如，在 renderSlot() 创建的 block fragment 中遇到非编译器生成的插槽
   *（即手写的 render 函数，这类函数应始终进行完整 diff），
   * 或手动 cloneVNodes 时使用。
   *
   * A special flag that indicates that the diffing algorithm should bail out
   * of optimized mode. For example, on block fragments created by renderSlot()
   * when encountering non-compiler generated slots (i.e. manually written
   * render functions, which should always be fully diffed)
   * OR manually cloneVNodes
   */
  BAIL = -2
}

/**
 * dev only flag -> name mapping
 */
export const PatchFlagNames = {
  [PatchFlags.TEXT]: `TEXT`,
  [PatchFlags.CLASS]: `CLASS`,
  [PatchFlags.STYLE]: `STYLE`,
  [PatchFlags.PROPS]: `PROPS`,
  [PatchFlags.FULL_PROPS]: `FULL_PROPS`,
  [PatchFlags.HYDRATE_EVENTS]: `HYDRATE_EVENTS`,
  [PatchFlags.STABLE_FRAGMENT]: `STABLE_FRAGMENT`,
  [PatchFlags.KEYED_FRAGMENT]: `KEYED_FRAGMENT`,
  [PatchFlags.UNKEYED_FRAGMENT]: `UNKEYED_FRAGMENT`,
  [PatchFlags.NEED_PATCH]: `NEED_PATCH`,
  [PatchFlags.DYNAMIC_SLOTS]: `DYNAMIC_SLOTS`,
  [PatchFlags.DEV_ROOT_FRAGMENT]: `DEV_ROOT_FRAGMENT`,
  [PatchFlags.HOISTED]: `HOISTED`,
  [PatchFlags.BAIL]: `BAIL`
}
